# Generated by Django 5.0.7 on 2024-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок статьи",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                ("slug", models.CharField(max_length=50, verbose_name="Индефикатор")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст статьи",
                        null=True,
                        verbose_name="Статья",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью статьи",
                        null=True,
                        upload_to="product/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату написания статьи",
                        null=True,
                        verbose_name="Дата написания статьи",
                    ),
                ),
                ("is_publication", models.BooleanField()),
                (
                    "count_views",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров статьи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
