# Generated by Django 5.0.7 on 2024-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_publication",
            field=models.BooleanField(default=True, verbose_name="Опубликовать?"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Индефикатор"
            ),
        ),
    ]
